api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "cart-attribute-function"
type = "function"
uid = "71867a88-bec9-cf49-06f4-f725ec628f42cb9a6ed5"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
